In [1]:
import os
os.chdir('../src/models/')
import sys
from dotenv import load_dotenv, find_dotenv
import numpy as np

sys.path.append(os.path.abspath("../.."))
# find .env automagically by walking up directories until it's found
dotenv_path = find_dotenv()
# load up the entries as environment variables
load_dotenv(dotenv_path)
# import pandas as pd

from src.code_snippets.dataprep.embeddings_preprocessing.data_preparation import (
    sentences_to_indices,
    pretrained_embedding_layer
)

from src.code_snippets.utils.abstract_classes import Trainer
from src.code_snippets.dataprep.embeddings_preprocessing.glove.reader import read_glove_file,get_word_index_dicts
from src.code_snippets.dataprep.embeddings_preprocessing.data_preparation import pretrained_embedding_layer
import random
from src.code_snippets.utils.data_handler import read_pickle

In [2]:

class ManyToOneSeqModel(Trainer):

    def __init__(self,train_data,val_data,embedding_dir):
        self.train_data = train_data
        self.val_data = val_data
        self.embedding_dir = embedding_dir
        self.gensim_model = read_glove_file(self.embedding_dir)
        self.word_to_index,self.index_to_words = get_word_index_dicts(self.gensim_model)
        
        self.m_X, self.n_X = self.train_data['X_indices_train'].shape
        self.m_X_aux, self.n_X_aux = self.train_data['X_aux_train'].shape
    
    def set_model(self):
        pretrained_embedding_layer(self.gensim_model, self.word_to_index)
    
    def save_model(self):
        pass
    def fit_model(self):
        pass
    def generate_metrics(self):
        pass

In [3]:
import tensorflow as tf
from tensorflow.keras.layers import Input,LSTM,Conv1D,Dropout, Dense
from tensorflow.keras import Model


In [4]:
seed = 100
random.seed(seed)
np.random.seed(seed)

In [5]:
train_data = read_pickle('../../data/processed/processed_data_train.pickle')
val_data = read_pickle('../../data/processed/processed_data_val.pickle')

In [7]:
train_data['X_indices'].shape

(809, 115)

In [28]:
StandardScaler_train = read_pickle('../../data/processed/StandardScaler_train.pickle')


In [29]:
temp = StandardScaler_train.inverse_transform(train_data['X_aux'])

In [42]:
temp.ARGmax(axis=0)

array([[145.        ,  33.        ,   1.        , ...,   3.03030303,
          9.09090909,  27.27272727],
       [355.        ,  71.        ,   1.        , ...,   8.45070423,
          5.63380282,  26.76056338],
       [ 92.        ,  21.        ,   1.        , ...,   0.        ,
          4.76190476,  28.57142857],
       ...,
       [333.        ,  67.        ,   1.        , ...,   2.98507463,
          4.47761194,  23.88059701],
       [104.        ,  23.        ,   1.        , ...,   8.69565217,
          0.        ,   4.34782609],
       [370.        ,  92.        ,   1.        , ...,   6.52173913,
          8.69565217,  17.39130435]])

In [50]:
raw_train[raw_train['comment_text'].apply(lambda x: ('FREEDOM' in x)&('ASSHOLE' in x)&('NAZI' in x))]

id                                       comment_text  \
94778  0fd85e97c0b88732  ASSHOLE \nYOU ARE AN ASSHOLE WIKI NAZI! \n\nFR...   

       toxic  severe_toxic  obscene  threat  insult  identity_hate  
94778      1             0        1       0       1              0

In [57]:
from src.code_snippets.dataprep.embeddings_preprocessing.glove.twitter_preprocessing import preprocessing


In [66]:
raw_train['comment_text'][94778]

'ASSHOLE \nYOU ARE AN ASSHOLE WIKI NAZI! \n\nFREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!\nFREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEhttp://en-US.www.mozilla.com/en-US/firefox/central/\nGetting StartedDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!\nFREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!\nFREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!\nFREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!\nFREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!\nFREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FREEDOM!FRE

In [71]:
preprocessing('FREEDOM!FREEDOM!FREEDOM')

'freedom <allcaps>  !freedom <allcaps>  !freedom <allcaps> '

In [26]:
tp.

array([4.74700000e+03, 8.50000000e+01, 0.00000000e+00, 4.94117647e+01,
       0.00000000e+00, 6.77647059e+02, 1.41176471e+01, 5.05882353e+01,
       2.35294118e+00, 0.00000000e+00, 1.17647059e+00])

In [11]:
a = []
for i in train_data['X_indices']:
    a.append(i[i!=0])


In [23]:
longest_comment = np.argmax([len(i) for i in a])
train_data['X_indices'][longest_comment]
print(longest_comment)

77421


In [33]:
train_data['X_indices'][longest_comment]

array([3.98700e+04, 1.91800e+03, 6.68737e+05, ..., 1.00000e+00,
       2.14421e+05, 1.91800e+03])

In [19]:
import pandas as pd
raw_train= pd.read_csv('../../data/interim/train.csv')

In [24]:
raw_train[raw_train]

id                                       comment_text  \
0       1293c8bb110e6efc  "\n\n Please do not vandalize pages, as you di...   
1       6b86eae945de4168  "However, Davis was one of many jazz musicians...   
2       63468eaa2d43cae5  hello \n\nim not sure of the proper way to add...   
3       2a3ea8e9e81d99dd  "I'm in on some controversy.  I came here beca...   
4       75ca0bc5b4f4fa70  I changed the subject heading to Talk:Sarah_Pa...   
...                  ...                                                ...   
153183  dc1a61190e0475dd  the joy of turning yourself from a Bavarian cr...   
153184  af8962ff812c1748  Image:Garma03.jpg\nI have tagged Image:Garma03...   
153185  d0058dd19c233604  "\nTesla stuff\n\nNotice how all those ""ugly ...   
153186  95df37d4a69b607d  I am assuming that there is no point trying to...   
153187  668ba87c1b6a3f31  "\nPlus, take a look! Have I made  any outing ...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
0           0             0        0       0       0              0  
1           0             0        0       0       0              0  
2           0             0        0       0       0              0  
3           0             0        0       0       0              0  
4           0             0        0       0       0              0  
...       ...           ...      ...     ...     ...            ...  
153183      0             0        0       0       0              0  
153184      0             0        0       0       0              0  
153185      0             0        0       0       0              0  
153186      0             0        0       0       0              0  
153187      0             0        0       0       0              0  

[153188 rows x 8 columns]

In [52]:
list(tp.st.tokenize())

In [20]:
from src.features.build_features import textProcessor


In [37]:
tp = textProcessor(
    data_dir='../../data/interim/val.csv',
    # TODO: Change embedding size
    embedding_dir='../../data/raw/pretrained_embeddings/glove.twitter.27B/glove.twitter.27B.25d.txt',
    nrows=1000,
)

tp.read()

W0421 17:52:27.652818 139690821285696 api.py:40] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /?properties=%7B%22outputFormat%22%3A+%22json%22%2C+%22annotators%22%3A+%22tokenize%2Cssplit%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ba926b438>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 3 seconds...


testing connection...


W0421 17:52:30.656558 139690821285696 api.py:40] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /?properties=%7B%22outputFormat%22%3A+%22json%22%2C+%22annotators%22%3A+%22tokenize%2Cssplit%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ba926bc50>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 3 seconds...


testing connection...


W0421 17:52:33.662531 139690821285696 api.py:40] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /?properties=%7B%22outputFormat%22%3A+%22json%22%2C+%22annotators%22%3A+%22tokenize%2Cssplit%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ba92484a8>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 3 seconds...


testing connection...


W0421 17:52:36.667307 139690821285696 api.py:40] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /?properties=%7B%22outputFormat%22%3A+%22json%22%2C+%22annotators%22%3A+%22tokenize%2Cssplit%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ba926bf60>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 3 seconds...


testing connection...


W0421 17:52:39.671648 139690821285696 api.py:40] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /?properties=%7B%22outputFormat%22%3A+%22json%22%2C+%22annotators%22%3A+%22tokenize%2Cssplit%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ba926ba90>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 3 seconds...


testing connection...
testing connection...
Server ready!


In [22]:
from nltk.tokenize import word_tokenize

In [23]:
from nltk.parse.corenlp import CoreNLPParser
st = CoreNLPParser()

In [24]:
tp.clean("comment_text", "comment_cleaned")

In [25]:
tp.post_processing_max_len

114

In [17]:
list(st.tokenize(tp.df.iloc[659]['comment_text']))

['I',
 "'m",
 'lifting',
 'a',
 'glass',
 ',',
 'myself',
 '.',
 'Voting',
 'just',
 'ended',
 'on',
 'the',
 'Italian',
 'page',
 ',',
 'and',
 'the',
 'page',
 'is',
 'maintained',
 '.',
 'Thank',
 'you',
 'for',
 'your',
 'help',
 'and',
 'advice',
 '!']

In [41]:
[tp.index_to_words[i] for i in train_data['X_indices'][longest_comment] if i!=0]

['asshole',
 '<allcaps>',
 'you',
 '<allcaps>',
 'are',
 '<allcaps>',
 'an',
 '<allcaps>',
 'asshole',
 '<allcaps>',
 'wiki',
 '<allcaps>',
 'nazi',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'free',
 '<allcaps>',
 '<url>',
 '/',
 'getting',
 '<unknown>',
 '<allcaps>',
 '!',
 'freedom',
 '<allcaps>',
 '!',
 'freedom'

In [32]:
train_data['X_indices'][0]

array([2.00000e+00, 4.82744e+05, 1.62203e+05, 4.24731e+05, 6.34784e+05,
       4.60382e+05, 1.73600e+03, 3.77230e+04, 6.68737e+05, 1.52288e+05,
       6.55001e+05, 6.02843e+05, 1.75537e+05, 6.07686e+05, 6.09967e+05,
       6.52183e+05, 1.81800e+03, 2.68863e+05, 6.68737e+05, 1.22517e+05,
       6.07686e+05, 1.62203e+05, 5.63885e+05, 1.73600e+03, 6.68737e+05,
       6.54139e+05, 5.91040e+04, 7.49640e+04, 2.15709e+05, 1.75571e+05,
       1.81800e+03, 9.83925e+05, 2.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.000

In [7]:
num_observations = len(train_data['X_aux_train'])
idx = np.arange(num_observations)

sample_portion = 0.01
sample_size = int(num_observations*sample_portion)
print(sample_size)

1224


In [8]:
np.random.seed(seed)
sampled_idx = np.random.choice(idx,sample_size,replace = False)

use_sample = False

if use_sample:
    train_data['X_indices_train'] = train_data['X_indices_train'][sampled_idx]
    train_data['X_aux_train'] = train_data['X_aux_train'][sampled_idx]
    train_data['y_train'] = train_data['y_train'][sampled_idx]
else:
    train_data['X_indices_train'] = train_data['X_indices_train']
    train_data['X_aux_train'] = train_data['X_aux_train']
    train_data['y_train'] = train_data['y_train']

In [11]:
trainer = ManyToOneSeqModel(train_data,
                            val_data,
                            "../../data/raw/pretrained_embeddings/glove.twitter.27B/glove.twitter.27B.50d.txt")


In [12]:
#TODO: uncomment this below
#sentence_indices = Input((trainer.n_X),dtype='int32')
sentence_indices = Input((100),dtype='int32')


# Create the embedding layer pretrained with GloVe Vectors (≈1 line)
embedding_layer = pretrained_embedding_layer(trainer.gensim_model,
                                             trainer.word_to_index)

# Propagate sentence_indices through your embedding layer
# (See additional hints in the instructions).
embeddings = embedding_layer(sentence_indices)   

X = LSTM(128,return_sequences=True)(embeddings)

X = Dropout(0.1,seed= seed)(X)

X = LSTM(128,return_sequences=False)(X)

X = Dropout(0.1,seed= seed)(X)

X = Dense(16,activation='relu')(X)

X = Dropout(0.1,seed= seed)(X)

X = Dense(1,activation='sigmoid')(X)


model = Model(sentence_indices,X)

In [13]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 100)]             0         
_________________________________________________________________
embedding (Embedding)        (None, 100, 50)           59675750  
_________________________________________________________________
lstm (LSTM)                  (None, 100, 128)          91648     
_________________________________________________________________
dropout (Dropout)            (None, 100, 128)          0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense (Dense)                (None, 16)                2064  

In [14]:
import tensorflow.keras.backend as K

def f1_metric(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    recall = true_positives / (possible_positives + K.epsilon())
    f1_val = 2*(precision*recall)/(precision+recall+K.epsilon())
    return f1_val


In [19]:
trainer.train_data['X_indices_train'].shape

(122484, 1870)

In [25]:
trainer.val_data['X_aux_val'].max(axis=0)

array([28.47401718,  2.56124698,  0.35331467,  8.74224234,  1.82307054,
       21.76854791,  3.38960009,  5.71984145,  8.26518656,  6.53318328,
        5.99123906])

In [26]:
trainer.val_data['X_aux_val'].shape

(5138, 11)

In [56]:
model.compile(loss='binary_crossentropy',metrics = [f1_metric])


In [58]:
model.fit(trainer.train_data['X_indices_train'][:,0:100],
          trainer.train_data['y_train'],
          epochs=50,
          batch_size=2**5,
          shuffle=True)

Train on 1531 samples
Epoch 1/50
1531/1531 [==============================] - 13s 9ms/sample - loss: 0.3509 - f1_metric: 0.0409
Epoch 2/50
1531/1531 [==============================] - 9s 6ms/sample - loss: 0.2919 - f1_metric: 0.2399
Epoch 3/50
1376/1531 [=========================>....] - ETA: 0s - loss: 0.2697 - f1_metric: 0.3746

KeyboardInterrupt: 

In [49]:
model.fit(trainer.train_data['X_indices_train'][:,0:100],
          trainer.train_data['y_train'][:,0:100],
          epochs=50,
          batch_size=2**5,
          shuffle=True)

Train on 1531 samples
Epoch 1/50
1531/1531 [==============================] - 266s 174ms/sample - loss: 0.3504 - f1_metric: 0.0372
Epoch 2/50
1531/1531 [==============================] - 276s 181ms/sample - loss: 0.2870 - f1_metric: 0.2918
Epoch 3/50
1531/1531 [==============================] - 262s 171ms/sample - loss: 0.2603 - f1_metric: 0.4333
Epoch 4/50
1531/1531 [==============================] - 286s 187ms/sample - loss: 0.2319 - f1_metric: 0.4627
Epoch 5/50
1531/1531 [==============================] - 324s 212ms/sample - loss: 0.2250 - f1_metric: 0.4811
Epoch 6/50
1531/1531 [==============================] - 345s 225ms/sample - loss: 0.2103 - f1_metric: 0.5469
Epoch 7/50
1531/1531 [==============================] - 362s 237ms/sample - loss: 0.2050 - f1_metric: 0.5221
Epoch 8/50
1531/1531 [==============================] - 354s 232ms/sample - loss: 0.1884 - f1_metric: 0.6368
Epoch 9/50
1531/1531 [==============================] - 289s 189ms/sample - loss: 0.1758 - f1_metric: 0.59

KeyboardInterrupt: 